//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrintController {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FingerPrintController.SqlCommands", typeof(SqlCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  id,
        ///        created_at,
        ///        updated_at,
        ///        ip,
        ///        port,
        ///        name,
        ///        net_state,
        ///        enabled,
        ///        extra,
        ///        deleted_at
        ///
        ///FROM    fingerprint_devices.
        /// </summary>
        internal static string select_fingerPrintDevices_all {
            get {
                return ResourceManager.GetString("select_fingerPrintDevices_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  id,
        ///        created_at,
        ///        updated_at,
        ///        user_id,
        ///        fingerprint_user_id,
        ///        fingerprint_sub_id,
        ///        image_url,
        ///        template,
        ///        deleted_at
        ///
        ///FROM    fingerprints.
        /// </summary>
        internal static string select_fingerPrints_all {
            get {
                return ResourceManager.GetString("select_fingerPrints_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  id,
        ///        created_at,
        ///        updated_at,
        ///        name,
        ///        ip,
        ///        number,
        ///        type,
        ///        gate,
        ///        state,
        ///        gategender_id,
        ///        gatepass_id,
        ///        zone_id,
        ///        gatedirect_id,
        ///        netState,
        ///        timepass,
        ///        timeserver,
        ///        deleted_at
        ///
        ///FROM    gatedevices.
        /// </summary>
        internal static string select_gate_devices_all {
            get {
                return ResourceManager.GetString("select_gate_devices_all", resourceCulture);
            }
        }
    }
}
